import { expect, test } from "bun:test";
import { renderData } from "../src/render.ts";

test("list results print as numbered rows with owner and link", () => {
	const text = renderData({
		results: [
			{ title: "Bun in 100 seconds", videoUrl: "https://y.test/1", channelName: "Fireship", thumbnailUrl: "https://i.test/1.jpg" },
			{ name: "Cafe", placeUrl: "https://m.test/2" },
		],
		cursor: "abc",
	});
	expect(text).toBe(
		[
			"1. Bun in 100 seconds - Fireship",
			"   https://y.test/1",
			"2. Cafe",
			"   https://m.test/2",
			"cursor: abc",
		].join("\n"),
	);
});

test("flat objects print as key value lines and empty lists say so", () => {
	expect(renderData({ videoId: "x", isAutoGenerated: true, text: "hello" })).toBe(
		"videoId: x\nisAutoGenerated: true\ntext: hello",
	);
	expect(renderData({ results: [] })).toBe("No results.");
});
