import type { EmptyState, OutputOptions, Thumbnail } from "./api.js";

export type CommentSortBy = "any" | "top" | "latest";
export type LiveChatType = "top" | "live";
export type LiveChatStatus =
	| "live"
	| "upcoming"
	| "replay"
	| "chat_disabled"
	| "not_live";

export interface VideoDetailsOptions extends OutputOptions {
	url: string;
}

export interface VideoTranscriptOptions extends OutputOptions {
	url: string;
	lang?: string;
}

export interface VideoCommentsOptions extends OutputOptions {
	url: string;
	sortBy?: CommentSortBy;
	continuationToken?: string;
}

export interface VideoRepliesOptions extends OutputOptions {
	continuationToken: string;
}

export interface VideoLiveChatOptions extends OutputOptions {
	url: string;
	chatType?: LiveChatType;
	continuationToken?: string;
}

export interface VideoDetails {
	id: string;
	type: "video";
	url: string;
	videoUrl: string;
	title: string;
	author: string | null;
	authorId: string | null;
	category: string | null;
	description: string | null;
	durationSec: number | null;
	durationText: string | null;
	isLive: boolean;
	likeCount: number | null;
	likeCountText: string | null;
	viewCount: number | null;
	viewCountText: string | null;
	publishedAt: string | null;
	tags: string[];
	thumbnails: Thumbnail[];
	chapters: Chapter[];
}

export interface Chapter {
	title: string;
	startMs: number;
	startSec: number;
}

export interface RelatedVideo {
	id: string;
	type: "video";
	url: string;
	videoUrl: string;
	title: string | null;
	author: string | null;
	authorId: string | null;
	durationSec: number | null;
	durationText: string | null;
	viewCount: number | null;
	viewCountText: string | null;
	publishedAt: string | null;
	publishedAtText: string | null;
	thumbnails: Thumbnail[];
}

export interface VideoDetailsData {
	videoId: string;
	video: VideoDetails;
	related: RelatedVideo[];
}

export interface TranscriptSegment {
	text: string;
	start: number;
	duration: number;
}

export interface TranscriptData {
	videoId: string;
	language: {
		code: string | null;
		name: string | null;
		isAutoGenerated: boolean;
	};
	isTranslated: boolean;
	availableTracks: Array<{
		languageCode: string;
		languageName: string;
		isAutoGenerated: boolean;
	}>;
	segments: TranscriptSegment[];
	text: string;
}

export interface Comment {
	id: string;
	text: string;
	author: string | null;
	authorId: string | null;
	authorThumbnail: string | null;
	hasChannelOwnerReplied: boolean;
	isChannelOwner: boolean;
	isHearted: boolean;
	isPinned: boolean;
	isVerified: boolean;
	publishedAt: string | null;
	publishedAtText: string | null;
	likeCount: number | null;
	likeCountText: string | null;
	replyCount: number | null;
	replyCountText: string | null;
	repliesToken: string | null;
}

export interface CommentList {
	videoId: string;
	sortBy: string;
	items: Comment[];
	continuationToken: string | null;
	hasMore: boolean;
	empty?: EmptyState | null;
}

export type CommentsData = CommentList;

export interface Reply
	extends Omit<Comment, "replyCount" | "replyCountText" | "repliesToken"> {}

export interface RepliesData {
	items: Reply[];
	continuationToken: string | null;
	hasMore: boolean;
	empty?: EmptyState | null;
}

export interface LiveChatMessage {
	id: string;
	text: string;
	author: string | null;
	authorId: string | null;
	timestampUsec: string | null;
	isOwner: boolean;
	isModerator: boolean;
	isVerified: boolean;
	superChatAmount: string | null;
	superChatCurrency: string | null;
}

export interface LiveChatData {
	videoId: string;
	status: LiveChatStatus;
	isLive: boolean;
	concurrentViewers: number | null;
	pollIntervalMs: number | null;
	messages: LiveChatMessage[];
	continuationToken: string | null;
	hasMore: boolean;
}
